region updates

diff --git a/actions/region-mapping/action.yml b/actions/region-mapping/action.yml
--- a/actions/region-mapping/action.yml
+++ b/actions/region-mapping/action.yml
@@ -1,44 +1,44 @@
 name: 'Region Mapping'
+description: 'Maps a location to region code and suffix'
 
-on:
-  workflow_call:
-    inputs:
-      location:
-        description: 'The Azure region to deploy resources.'
-        required: true
-        type: string
+inputs:
+  location:
+    description: 'The Azure region to deploy resources.'
+    required: true
+    type: string
 
-jobs:
-  map_region:
-    runs-on: ubuntu-latest
-    outputs:
-      region_code: ${{ steps.set_output.outputs.region_code }}
-      region_suffix: ${{ steps.set_output.outputs.region_suffix }}
+outputs:
+  region_code:
+    description: 'The Azure region code'
+  region_suffix:
+    description: 'The short suffix for the region'
 
-   steps:
-      - name: Map region and suffix
-        id: set_output
-        run: |
-          location="${{ github.event.inputs.location }}"
+runs:
+  using: "composite"
+  steps:
+    - name: Map region and suffix
+      shell: bash
+      run: |
+        location="${{ inputs.location }}"
 
-          case "$location" in
-            "South Central US")
-              region_code="southcentralus"
-              region_suffix="scus"
-              ;;
-            "East US")
-              region_code="eastus"
-              region_suffix="eus"
-              ;;
-            "Europe")
-              region_code="europe"
-              region_suffix="eu"
-              ;;            
-            *)
-              echo "Error: Unrecognized location '$location'."
-              exit 1
-              ;;
-          esac
+        case "$location" in
+          "South Central US")
+            region_code="southcentralus"
+            region_suffix="scus"
+            ;;
+          "East US")
+            region_code="eastus"
+            region_suffix="eus"
+            ;;
+          "Europe")
+            region_code="europe"
+            region_suffix="eu"
+            ;;            
+          *)
+            echo "Error: Unrecognized location '$location'."
+            exit 1
+            ;;
+        esac
 
-          echo "::set-output name=region_code::$region_code"
-          echo "::set-output name=region_suffix::$region_suffix"
+        echo "region_code=$region_code" >> $GITHUB_OUTPUT
+        echo "region_suffix=$region_suffix" >> $GITHUB_OUTPUT
