split steps

diff --git a/actions/sonarqube-scanner/action.yml b/actions/sonarqube-scanner/action.yml
--- a/actions/sonarqube-scanner/action.yml
+++ b/actions/sonarqube-scanner/action.yml
@@ -86,9 +86,34 @@ runs:
         mkdir -p ./.sonar/scanner
         dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
 
-    - name: Build and analyze
+      - name: Check URL Access
+        shell: bash
+        run: |
+          URL="${{ inputs.sonar-host-url }}"
+          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
+          if [ "$HTTP_STATUS" -ne 200 ]; then
+            echo "Failed to access $URL, status code: $HTTP_STATUS"
+            exit 1
+          else
+            echo "Successfully accessed $URL, status code: $HTTP_STATUS"
+          fi
+
+    - name: SonarQubeAnalyze
       shell: bash      
       run: |
-        ./.sonar/scanner/dotnet-sonarscanner begin /k:${{ inputs.project-key }} /d:sonar.token="${{ inputs.sonar-token }}" /d:sonar.host.url="${{ inputs.sonar-host-url }}" /d:sonar.projectBaseDir=${{ inputs.working-directory }}
+        ./.sonar/scanner/dotnet-sonarscanner begin \
+        /k:${{ inputs.project-key }} \
+        /d:sonar.token="${{ inputs.sonar-token }}" \
+        /d:sonar.host.url="${{ inputs.sonar-host-url }}" \
+        /d:sonar.projectBaseDir=${{ inputs.working-directory }}         
+
+    - name: Build 
+      shell: bash      
+      run: |        
         dotnet build ${{ inputs.solution-name }} --configuration Release 
+
+    - name: SonarQubeAnalyze
+      shell: bash      
+      run: |        
         ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ inputs.sonar-token }}" | tee logs.txt
+        
