debug

diff --git a/actions/release-notes/action.yml b/actions/release-notes/action.yml
--- a/actions/release-notes/action.yml
+++ b/actions/release-notes/action.yml
@@ -50,6 +50,29 @@ runs:
         echo "WIKI_URL=$WIKI_URL" >> $GITHUB_ENV
         echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
 
+    - name: Test Write
+      shell: bash    
+      env:
+        AuthToken: ${{ inputs.auth_token }}        
+      run: |       
+
+        RESPONSE=$(curl -v -X PUT \
+         -H "Authorization: Basic $(echo -n user:$AuthToken | base64)" \
+         -H "Content-Type: application/json" \
+         -d '{"content": "Test content"}' \
+         "https://dev.azure.com/ABSDigital/Common%20Core/_apis/wiki/wikis/Common-Core.wiki/pages?path=/MyTestPage&api-version=7.1-preview.1")              
+          
+
+        RESPONSE_CODE="${RESPONSE: -3}"
+        RESPONSE_BODY="${RESPONSE%???}"
+
+        echo "Response Code: $RESPONSE_CODE"
+        echo "Response Body: $RESPONSE_BODY"
+
+        if [ "$RESPONSE_CODE" -ne 200 ]; then
+          echo "Failed to update the Wiki page. Response code: $RESPONSE_CODE"
+          exit 1
+        fi     
 
     - name: Check if environment page exists and create if not 
       shell: bash    
