update

diff --git a/actions/release-notes/action.yml b/actions/release-notes/action.yml
--- a/actions/release-notes/action.yml
+++ b/actions/release-notes/action.yml
@@ -89,7 +89,7 @@ runs:
            RESPONSE=$(curl -X PUT \
             -H "Authorization: Basic $(echo -n user:$AuthToken | base64)" \
             -H "Content-Type: application/json" \
-            -d '{"content": "Test content"}' \
+            -d "$JSON_CONTENT" \
             "$WIKI_URL")              
           
 
@@ -108,56 +108,46 @@ runs:
           echo "Environment page '${ENVIRONMENT}' already exists."
         fi
 
+    - name: Download Wiki page content
+      env:
+        AuthToken: ${{ inputs.auth_token }}
+      run: |
+       
+        curl -H "Authorization: Basic $(echo -n :$AuthToken | base64)" \
+             -H "Accept: application/json" \
+             "$WIKI_URL" | jq -r '.content' > wiki_page.html
 
+    - name: Update or Add Solution in the HTML table
+      run: |
+        SOLUTION_NAME="${{ inputs.solution_name }}"
+        NEW_VERSION="${{ inputs.version }}"
+        FILE="wiki_page.html"
 
-    # - name: Download Wiki page content
-    #   env:
-    #     AUTH_TOKEN: ${{ secrets.AZURE_WIKI_PAT }}
-    #   run: |
-    #     WIKI_URL_ROOT="${{ inputs.wiki_url_root }}"
-    #     ROOT_PAGE="${{ inputs.wiki_page }}"
-    #     ENVIRONMENT="${{ inputs.environment }}"
-    #     WIKI_URL="${WIKI_URL_ROOT}/${ROOT_PAGE}/${ENVIRONMENT}"
+        # Check if the table exists
+        if ! grep -q "<table>" $FILE; then
+          echo "Table not found, creating a new table."
+          echo '<table><tr><th>Solution Name</th><th>Version</th></tr></table>' > $FILE
+        fi
 
-    #     curl -H "Authorization: Basic $(echo -n :${{ secrets.AZURE_WIKI_PAT }} | base64)" \
-    #          -H "Accept: application/json" \
-    #          "$WIKI_URL" | jq -r '.content' > wiki_page.html
+        # Check if the solution already exists in the table
+        if grep -q "<td>${SOLUTION_NAME}</td>" $FILE; then
+          echo "Solution found, updating the version."
+          sed -i "/<td>${SOLUTION_NAME}<\/td>/!b;n;s/<td>.*<\/td>/<td>${NEW_VERSION}<\/td>/" $FILE
+        else
+          echo "Solution not found, adding new entry."
+          sed -i "/<\/table>/i <tr><td>${SOLUTION_NAME}</td><td>${NEW_VERSION}</td></tr>" $FILE
+        fi
 
-    # - name: Update or Add Solution in the HTML table
-    #   run: |
-    #     SOLUTION_NAME="${{ github.event.inputs.solution_name }}"
-    #     NEW_VERSION="${{ github.event.inputs.version }}"
-    #     FILE="wiki_page.html"
-
-    #     # Check if the table exists
-    #     if ! grep -q "<table>" $FILE; then
-    #       echo "Table not found, creating a new table."
-    #       echo '<table><tr><th>Solution Name</th><th>Version</th></tr></table>' > $FILE
-    #     fi
-
-    #     # Check if the solution already exists in the table
-    #     if grep -q "<td>${SOLUTION_NAME}</td>" $FILE; then
-    #       echo "Solution found, updating the version."
-    #       sed -i "/<td>${SOLUTION_NAME}<\/td>/!b;n;s/<td>.*<\/td>/<td>${NEW_VERSION}<\/td>/" $FILE
-    #     else
-    #       echo "Solution not found, adding new entry."
-    #       sed -i "/<\/table>/i <tr><td>${SOLUTION_NAME}</td><td>${NEW_VERSION}</td></tr>" $FILE
-    #     fi
-
-    # - name: Update Wiki page content
-    #   env:
-    #     AUTH_TOKEN: ${{ secrets.AZURE_WIKI_PAT }}
-    #   run: |
-    #     WIKI_URL_ROOT="${{ inputs.wiki_url_root }}"
-    #     ROOT_PAGE="${{ inputs.wiki_page }}"
-    #     ENVIRONMENT="${{ inputs.environment }}"
-    #     WIKI_URL="${WIKI_URL_ROOT}/${ROOT_PAGE}/${ENVIRONMENT}"
-
-    #     UPDATED_CONTENT=$(<wiki_page.html)
-    #     JSON_CONTENT=$(jq -n --arg content "$UPDATED_CONTENT" '{content: $content}')
+    - name: Update Wiki page content
+      env:
+        AuthToken: ${{ inputs.auth_token }}
+      run: |
         
-    #     curl -X PUT \
-    #          -H "Authorization: Basic $(echo -n :${{ secrets.AZURE_WIKI_PAT }} | base64)" \
-    #          -H "Content-Type: application/json" \
-    #          -d "$JSON_CONTENT" \
-    #          "$WIKI_URL"
+        UPDATED_CONTENT=$(<wiki_page.html)
+        JSON_CONTENT=$(jq -n --arg content "$UPDATED_CONTENT" '{content: $content}')
+        
+        curl -X PUT \
+             -H "Authorization: Basic $(echo -n :$AuthToken | base64)" \
+             -H "Content-Type: application/json" \
+             -d "$JSON_CONTENT" \
+             "$WIKI_URL"
