Feature/ado 116968 release notes (#268)
* draft action

* minor

* minor 2

* test

* minor

* shell

* test

* shell

* token

* typo

* authToken

* test

* test

* test

* test

* test user

* debug

* debug

* debug

* test

* test2

* debug 2

* update

* bash

* debug info

* debug3

* debug 4

* debug4

* minor

* test

* .

* test

* debug

* test

* test

* test3

* debug

* test again

* dd

* rr

* test

* test

* test

* text/html

* response

* td

* td

* test

* tt

* test

* tr

* debug info

* test

* debug

* test patch

* put

* etag

* pageInfo

* page id

* test

* etag

* test

* etag

* downgrade api version

* add

* test

* test

* debug

* test agent

* redirect

* test

* test

* z

* headers.txt

* .

* clean

* update file

* test2

* new row

* test2

* test4

* test

* rr

* test1

* test

* sed

* test

* read tagVesrion

* typo

* test

* test

* test

* test

* test

* test

* tests

* test

* test

* test4

* test

* add Function name

* minor updates

* add extra adjusting

* bug

* max-parallel: 1

* test

* test

* AZURE_WIKI_PAT

* header color

* adjust

* typo

diff --git a/.github/workflows/cc-deploy-function-apps.yml b/.github/workflows/cc-deploy-function-apps.yml
--- a/.github/workflows/cc-deploy-function-apps.yml
+++ b/.github/workflows/cc-deploy-function-apps.yml
@@ -49,12 +49,16 @@ on:
         required: true
       AZURE_SUBSCRIPTION_ID:
         required: true
+      AZURE_WIKI_PAT:
+        required: true
 
 jobs: 
   deploy:    
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     name: Deploy
+    outputs:
+      matrix: ${{ steps.setup.outputs.matrix }}
     steps:
       - name: Set unique directory names
         id: unique-path
@@ -99,7 +103,36 @@ jobs:
         run: |
             $destinationPath = "${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/functions"
             $zipFilePath = "${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/${{ inputs.artifactFunctions }}.zip"        
-            Expand-Archive -Path $zipFilePath -DestinationPath $destinationPath         
+            Expand-Archive -Path $zipFilePath -DestinationPath $destinationPath     
+            
+            # Find the first zip file inside the expanded folder
+            $innerZipPath = Get-ChildItem -Path $destinationPath -Filter '*.zip' | Select-Object -First 1
+
+            if ($null -ne $innerZipPath) {
+              
+                $innerDestinationPath = Join-Path -Path $destinationPath -ChildPath 'inner-unzipped'
+                New-Item -ItemType Directory -Path $innerDestinationPath -Force | Out-Null
+                
+                Expand-Archive -Path $innerZipPath.FullName -DestinationPath $innerDestinationPath                
+               
+            } else {
+                Write-Error "No inner zip file found."
+                exit 1
+            }
+
+      - name: Read tagVersion from host.json
+        id: read_tag_version
+        working-directory: ${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/functions/inner-unzipped
+        shell: bash
+        run: |
+           if [ -f "host.json" ]; then
+              TAG_VERSION=$(jq -r '.tagVersion' host.json)
+              echo "tagVersion: $TAG_VERSION"
+              echo "::set-output name=tag_version::$TAG_VERSION"
+           else
+              echo "host.json not found."
+              exit 1
+           fi
 
       - name: Login via Azure CLI
         uses: azure/login@v2
@@ -108,19 +141,31 @@ jobs:
 
       - name: Azure Function App Zip Deploy
         shell: bash
+        id: setup
         run: |         
           artifactPath="${{ github.workspace }}/downloaded-artifacts-conf-${{ steps.unique-path.outputs.uniquePathSuffix }}/${{inputs.artifactConfigFile }}"
           functionConfigs=$(jq -c '.[]' <"$artifactPath")
+          matrix_json="[]"
+          version=${{ steps.read_tag_version.outputs.tag_version }}
 
           for config in $functionConfigs; do
             use=$(echo $config | jq -r '.Use')
             if [ "$use" = "true" ]; then
               functionName=$(echo "$config" | jq -r '.AZURE_FUNCTIONAPP_NAME') 
               function_name_suffix=${{ inputs.function_name_suffix }}
+              solutionName=$(echo "$config" | jq -r '.FUNCTION_PROJECT_PATH')
               
               if [ -n "${{ inputs.function_name_suffix }}" ]; then
-                functionName="${functionName}-${function_name_suffix}"
+                functionName="${functionName}-${function_name_suffix}"                
               fi
+
+              matrix_entry=$(jq -n \
+                --arg functionName "$functionName" \
+                --arg version "$version" \
+                --arg solutionName "$solutionName" \
+                '{functionName: $functionName, version: $version, solutionName: $solutionName}')
+              
+              matrix_json=$(echo "$matrix_json" | jq --argjson entry "$matrix_entry" '. + [$entry]')
                          
               artifactName=$(echo $config | jq -r '.Name')
               zipFilePath="${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/functions/${artifactName}.zip"
@@ -129,3 +174,31 @@ jobs:
               az functionapp deployment source config-zip -g ${{ inputs.resource_group_name }} -n $functionName --src $zipFilePath
             fi
           done  
+          echo "::set-output name=matrix::$(echo $matrix_json | jq -c .)"     
+
+  log:
+    name: Update Wiki
+    needs: deploy
+    if: ${{ needs.deploy.outputs.matrix != '[]' }}
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    strategy:
+      matrix: 
+        include: ${{ fromJson(needs.deploy.outputs.matrix) }}
+      max-parallel: 1
+    steps:
+      - name: Check Parameters
+        env:
+          MATRIX: ${{ toJSON(matrix) }}          
+        run: |
+          echo "MATRIX: $(jq -r -c '.' <<< "$MATRIX")"         
+      - name: publish release notes
+        uses: abs-wavesight/cc-platform/actions/release-notes
+        with:
+          solution_name: ${{ matrix.solutionName }}
+          az_func_name: ${{ matrix.functionName }}
+          version: ${{ matrix.version }}
+          wiki_page: "Common Core/Cloud Platform/Deploy"
+          environment: ${{ github.event.inputs.ENVIRONMENT }}
+          auth_token: ${{ secrets.AZURE_WIKI_PAT }}
+
