read tagVesrion

diff --git a/.github/workflows/cc-deploy-function-apps.yml b/.github/workflows/cc-deploy-function-apps.yml
--- a/.github/workflows/cc-deploy-function-apps.yml
+++ b/.github/workflows/cc-deploy-function-apps.yml
@@ -55,6 +55,8 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     name: Deploy
+    outputs:
+      matrix: ${{ steps.prepare-configs.outputs.matrix }}
     steps:
       - name: Set unique directory names
         id: unique-path
@@ -99,7 +101,36 @@ jobs:
         run: |
             $destinationPath = "${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/functions"
             $zipFilePath = "${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/${{ inputs.artifactFunctions }}.zip"        
-            Expand-Archive -Path $zipFilePath -DestinationPath $destinationPath         
+            Expand-Archive -Path $zipFilePath -DestinationPath $destinationPath     
+            
+            # Find the first zip file inside the expanded folder
+            $innerZipPath = Get-ChildItem -Path $destinationPath -Filter '*.zip' | Select-Object -First 1
+
+            if ($null -ne $innerZipPath) {
+              
+                $innerDestinationPath = Join-Path -Path $destinationPath -ChildPath 'inner-unzipped'
+                New-Item -ItemType Directory -Path $innerDestinationPath -Force | Out-Null
+                
+                Expand-Archive -Path $innerZipPath.FullName -DestinationPath $innerDestinationPath                
+               
+            } else {
+                Write-Error "No inner zip file found."
+                exit 1
+            }
+
+      - name: Read tagVersion from host.json
+        id: read_tag_version
+        working-directory: ${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/functions/inner-unzipped
+        shell: bash
+        run: |
+           if [ -f "host.json" ]; then
+              TAG_VERSION=$(jq -r '.tagVersion' host.json)
+              echo "tagVersion: $TAG_VERSION"
+              echo "::set-output name=tag_version::$TAG_VERSION"
+           else
+              echo "host.json not found."
+              exit 1
+           fi
 
       - name: Login via Azure CLI
         uses: azure/login@v2
@@ -111,6 +142,8 @@ jobs:
         run: |         
           artifactPath="${{ github.workspace }}/downloaded-artifacts-conf-${{ steps.unique-path.outputs.uniquePathSuffix }}/${{inputs.artifactConfigFile }}"
           functionConfigs=$(jq -c '.[]' <"$artifactPath")
+          matrix_json="[]"
+          version=${{ steps.read_tag_version.outputs.tag_version }}
 
           for config in $functionConfigs; do
             use=$(echo $config | jq -r '.Use')
@@ -121,6 +154,13 @@ jobs:
               if [ -n "${{ inputs.function_name_suffix }}" ]; then
                 functionName="${functionName}-${function_name_suffix}"
               fi
+
+              matrix_entry=$(jq -n \
+                --arg functionName "$functionName" \
+                --arg version "$version" \
+                '{functionName: $functionName, version: $version}')
+              
+              matrix_json=$(echo "$matrix_json" | jq --argjson entry "$matrix_entry" '. + [$entry]')
                          
               artifactName=$(echo $config | jq -r '.Name')
               zipFilePath="${{ github.workspace }}/downloaded-artifacts-func-${{ steps.unique-path.outputs.uniquePathSuffix }}/functions/${artifactName}.zip"
@@ -129,3 +169,22 @@ jobs:
               az functionapp deployment source config-zip -g ${{ inputs.resource_group_name }} -n $functionName --src $zipFilePath
             fi
           done  
+          echo "::set-output name=matrix::$matrix_json"
+
+  log:
+     name: Update Wiki
+     needs: deploy
+     if: needs.deploy.outputs.outputs.matrix != '[]'
+     runs-on: ubuntu-latest
+     strategy:
+       matrix: ${{ fromJson(needs.deploy.outputs.outputs.matrix) }}
+     steps:
+      - name: Test
+        uses: abs-wavesight/cc-platform/actions/release-notes@feature/ADO-116968-release-notes
+        with:
+          solution_name: "Tenant adapter2 "
+          version: "1.0.2" # ${{ inputs.USE_VERSION }}
+          wiki_page: "Common%20Core/Cloud%20Platform/Deploy"
+          environment: ${{ github.event.inputs.ENVIRONMENT }}
+          auth_token: ${{ secrets.AZURE_WIKI_PAT }}
+
