Add windows & linux sonar analysis scripts

diff --git a/.github/workflows/shared-dotnet-build.yml b/.github/workflows/shared-dotnet-build.yml
--- a/.github/workflows/shared-dotnet-build.yml
+++ b/.github/workflows/shared-dotnet-build.yml
@@ -54,7 +54,24 @@ on:
         required: false
         type: string
         default: '7.0.x'
-        description: .NET SDK Version        
+        description: .NET SDK Version
+
+      # SonarQube Input Parameters
+      sonar-project-key:
+        required: true
+        description: "Reposiroty ID in SonarQube"
+        type: string
+      run-sonar-scan:
+        required: true
+        description: "Boolean to run sonarqube (true) or not (false)"
+        type: boolean
+        default: false
+      sonar-exclusion-paths:
+        required: false
+        description: "Comma separated list of paths to exclude from SonarQube analysis"
+        type: string
+        default: ""
+
 
 env:
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
@@ -71,9 +88,7 @@ defaults:
 jobs:
   build:
     name: Build & Run Tests
-
     runs-on: windows-2019
-
     steps:
 
       - name: Dump context
@@ -81,7 +96,7 @@ jobs:
 
       - name: Checkout branch with Submodules - ${{ inputs.use-submodules }}
         if: inputs.use-submodules == true
-        uses: actions/checkout@v3        
+        uses: actions/checkout@v4        
         with:
           submodules: true
           fetch-depth: 0
@@ -106,6 +121,10 @@ jobs:
         with:
           dotnet-version: ${{ inputs.dotnet-version}}
 
+      - name: .NET Version
+        shell: bash
+        run: dotnet --version
+
       - name: Install docker-compose
         if: inputs.install-docker-compose == true
         run: Start-BitsTransfer -Source "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-windows-x86_64.exe" -Destination "C:\ProgramData\Chocolatey\bin\docker-compose.exe"
@@ -127,7 +146,124 @@ jobs:
         working-directory: ${{ inputs.solution-directory }}
         run: dotnet restore ${{ inputs.solution-name }} --packages ${{ env.NUGET_PACKAGE_PATH }}
 
-      - name: Build
+      # ------------------- CONFIGURE SONARQUBE ------------------- #
+
+      - name: Build Solution w/ SonarQube Analysis - WINDOWS
+        uses: abs-wavesight/cc-platform/actions/sonarqube-scanner-windows@feature/sonar-scan
+        if: inputs.run-sonar-scan == true
+        with:
+          solution-directory: ${{ inputs.solution-directory }}
+          solution-name: ${{ inputs.solution-name }}
+          sonar-project-key: ${{ inputs.sonar-project-key }}
+          sonar-token: ${{ secrets.SONAR_TOKEN }}
+          sonar-exclusion-paths: ${{ inputs.sonar-exclusion-paths }}
+
+      # - name: Build Solution w/ SonarQube Analysis - LINUX
+      #   uses: abs-wavesight/cc-platform/actions/sonarqube-scanner-linux@feature/sonar-scan
+      #   if: inputs.run-sonar-scan == true
+      #   with:
+      #     solution-directory: ${{ inputs.solution-directory }}
+      #     solution-name: ${{ inputs.solution-name }}
+      #     sonar-project-key: ${{ inputs.sonar-project-key }}
+      #     sonar-token: ${{ secrets.SONAR_TOKEN }}
+      #     sonar-exclusion-paths: ${{ inputs.sonar-exclusion-paths }}
+
+      # - name: Run SonarQube Code Scan - ${{ inputs.run-sonar-scan }}
+      #   if: inputs.run-sonar-scan == true
+      #   run: echo "PREPARING SONARQUBE FOR CODE ANALYSIS"
+      
+      # - name: Set up JDK 17
+      #   if: inputs.run-sonar-scan == true
+      #   uses: actions/setup-java@v4
+      #   with:
+      #     path: ${{ inputs.solution-directory }}
+      #     distribution: "adopt"
+      #     java-version: 17
+
+      # - name: Cache SonarQube packages
+      #   if: inputs.run-sonar-scan == true
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ${{ inputs.solution-directory }}/.sonar/cache
+      #     key: ${{ runner.os }}-sonar
+      #     restore-keys: ${{ runner.os }}-sonar
+
+      # - name: Cache SonarQube scanner
+      #   if: inputs.run-sonar-scan == true
+      #   id: cache-sonar-scanner
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ${{ inputs.solution-directory }}/.sonar/scanner
+      #     key: ${{ runner.os }}-sonar-scanner
+      #     restore-keys: ${{ runner.os }}-sonar-scanner
+
+      # - name: Install SonarQube scanner
+      #   if: inputs.run-sonar-scan == true
+      #   # if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+      #   working-directory: ${{ inputs.solution-directory }}
+      #   shell: bash
+      #   run: |
+      #     mkdir -p ./.sonar/scanner
+      #     dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
+      #   # run: |
+      #   #   if inputs.run-sonar-scan == true; then
+      #   #     mkdir -p ./.sonar/scanner
+      #   #     dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
+      #   #   else
+      #   #     echo "SonarQube Scanner is NOT ENABLED"
+      #   #   fi
+
+      # - name: Check SonareQube URL Access
+      #   if: inputs.run-sonar-scan == true
+      #   shell: bash
+      #   run: |
+      #     URL="https://sonarqube.absns.cloud"
+      #     HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
+      #     if [ "$HTTP_STATUS" -ne 200 ]; then
+      #       echo "Failed to access $URL, status code: $HTTP_STATUS"
+      #       exit 1
+      #     else
+      #       echo "Successfully accessed $URL, status code: $HTTP_STATUS"
+      #     fi
+
+      # # ------  BUILD SOLUTION with SONARQUBE ANALYSIS-------- #
+
+      # - name: Build Solution w/ SonarQube Analysis
+      #   if: inputs.run-sonar-scan == true
+      #   working-directory: ${{ inputs.solution-directory }}
+      #   # ADDTIONAL SONAR PARAMETERS
+      #   # -d:sonar.qualitygate.wait=true \
+      #   # -d:sonar.qualitygate.timeout=500 \
+      #   # -d:sonar.pullrequest.key=${{ github.event.pull_request.number }} \
+      #   # -d:sonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
+      #   # -d:sonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
+      #   shell: bash
+      #   run: |
+      #     # Begin SonarQube Analysis
+      #     ./.sonar/scanner/dotnet-sonarscanner begin \
+      #       -k:${{ inputs.sonar-project-key }} \
+      #       -d:sonar.token=${{ secrets.SONAR_TOKEN }} \
+      #       -d:sonar.host.url="https://sonarqube.absns.cloud" \
+      #       -d:sonar.ws.timeout=500 \
+      #       -d:sonar.projectBaseDir=D:/a/cc-cloud-tenant-adapters/cc-cloud-tenant-adapters/ \
+      #       -d:sonar.branch.name=${{ github.event.pull_request.head.ref }}
+
+      #     # Build .NET Project
+      #     dotnet build ${{ inputs.solution-name }} -c Release --no-restore
+
+      #     # End SonarQube Analysis
+      #     ./.sonar/scanner/dotnet-sonarscanner end -d:sonar.token=${{ secrets.SONAR_TOKEN }} | tee sonar-logs.txt   
+
+      # # - name: "Upload Sonar Report File"
+      # #   uses: actions/upload-artifact@v4
+      # #   with:
+      # #     name: sonar-logs
+      # #     path: ${{ inputs.solution-directory }}/.sonar/sonar-logs.txt
+
+      # ---------------------------------------------------------- #
+
+      - name: Build Solution
+        if: inputs.run-sonar-scan == false
         working-directory: ${{ inputs.solution-directory }}
         run: dotnet build ${{ inputs.solution-name }} -c Release --no-restore
 
